# Generated by Django 5.2.9 on 2026-05-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_lessoncontent_video_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('checkpointid', models.AutoField(db_column='CheckpointID', primary_key=True, serialize=False)),
                ('paragraph_index', models.IntegerField(db_column='ParagraphIndex', help_text='رقم الفقرة (يبدأ من 0)')),
                ('question', models.CharField(db_column='Question', help_text='سؤال قصير للفقرة', max_length=500)),
                ('option_a', models.CharField(db_column='OptionA', help_text='الخيار الأول', max_length=300)),
                ('option_b', models.CharField(db_column='OptionB', help_text='الخيار الثاني', max_length=300)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B')], db_column='CorrectAnswer', help_text='الإجابة الصحيحة (للمعلم فقط)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('lessonid', models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent')),
            ],
            options={
                'db_table': 'Checkpoint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCheckpointAnswer',
            fields=[
                ('answerid', models.AutoField(db_column='AnswerID', primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B')], db_column='SelectedAnswer', help_text='الإجابة التي اختارها الطالب', max_length=10)),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_column='AnsweredAt')),
                ('checkpoint', models.ForeignKey(db_column='CheckpointID', on_delete=django.db.models.deletion.CASCADE, to='learning.checkpoint')),
                ('sessionid', models.ForeignKey(blank=True, db_column='SessionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'StudentCheckpointAnswer',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['lessonid'], name='idx_chk_lesson'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['lessonid', 'paragraph_index'], name='idx_chk_lesson_para'),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('lessonid', 'paragraph_index')},
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['studentid'], name='idx_stud_chk_ans'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['checkpoint'], name='idx_chk_ans_chk'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['sessionid'], name='idx_chk_ans_sess'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcheckpointanswer',
            unique_together={('checkpoint', 'studentid', 'sessionid')},
        ),
    ]
