# Generated by Django 5.2.9 on 2026-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_checkpoint_studentcheckpointanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='response_time',
            field=models.FloatField(blank=True, db_column='ResponseTime', help_text='المدة الزمنية التي احتاجها الطالب للاختيار (بالثواني)', null=True),
        ),
    ]
