# Generated by Django 5.2.9 on 2026-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0048_vrlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrlesson',
            name='vr_attachment',
            field=models.FileField(blank=True, db_column='VR_Attachment', help_text='مرفق إضافي للواقع الافتراضي (PDF, ZIP, أو أي ملف آخر)', null=True, upload_to='vr_attachments/'),
        ),
        migrations.AlterField(
            model_name='vrlesson',
            name='design_platform_url',
            field=models.URLField(db_column='DesignPlatformURL', default='https://aistudio.google.com/apps/ea0032ea-b331-4cc8-a5fd-e59bbce58fbe?fullscreenApplet=true&showPreview=true&showAssistant=true', help_text='رابط منصة تصميم بيئة الواقع الافتراضي', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vrlesson',
            name='is_published',
            field=models.BooleanField(db_column='IsPublished', default=False, help_text='هل تم نشر تجربة الواقع الافتراضي للطالب؟'),
        ),
        migrations.AlterField(
            model_name='vrlesson',
            name='vr_url',
            field=models.URLField(db_column='VR_URL', help_text='رابط منصة الواقع الافتراضي المصمم من قبل المعلم', max_length=1000),
        ),
    ]
