# Generated by Django 5.2.9 on 2026-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0049_lessoncontent_video_published_vrlesson_vr_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrlesson',
            name='vr_url',
            field=models.URLField(blank=True, db_column='VR_URL', help_text='رابط منصة الواقع الافتراضي المصمم من قبل المعلم', max_length=1000, null=True),
        ),
    ]
