# Generated by Django 5.1.6 on 2026-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0051_lessoncontent_video_published_studentvrinteraction'),
    ]

    operations = [
        # تم تفريغ العمليات لمنع خطأ DuplicateColumn لأن العمود موجود بالفعل في قاعدة البيانات
    ]